import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import client from "tina/__generated__/client";
import { PostQuery } from "tina/__generated__/types";
import { Exact } from "tina/__generated__/types";
import { TinaMarkdown } from "tinacms/dist/rich-text";

type Query = {
  data: PostQuery;
  errors?:
  | {
    message: string;
    locations: {
      line: number;
      column: number;
    }[];
    path: string[];
  }[]
  | undefined;
  variables: Exact<{
    relativePath: string;
  }>;
  query: string;
};

export default function Home() {
  const [data, setData] = useState<Query>();

  useEffect(() => {
    async function getPost() {
      const post = await client.queries.post({
        relativePath: "hello-world.md",
      });
      setData(post);
    }
    void getPost();
  }, []);

  console.log(data);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Create <span className="text-[hsl(280,100%,70%)]">T3</span> App
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">First Steps →</h3>
              <div className="text-lg">
                Just the basics - Everything you need to know to set up your
                database and authentication.
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Documentation →</h3>
              <div className="text-lg">
                Learn more about Create T3 App, the libraries it uses, and how
                to deploy it.
              </div>
            </Link>
          </div>
          <div className="flex max-w-prose flex-col gap-4 text-white">
            <h2 className="text-3xl">{data?.data.post.title}</h2>
            {/* eslint-disable-next-line @typescript-eslint/no-unsafe-assignment */}
            <TinaMarkdown content={data?.data.post.body} />
          </div>
        </div>
      </main>
    </>
  );
}
